CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(20) NOT NULL
);
CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);
CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar(50) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);
CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(200) NOT NULL,
  "teacher" int NOT NULL,
  "categorie_id" int NOT NULL
);
CREATE TABLE "students_courses" (
  "student" int NOT NULL,
  "course_id" int NOT NULL
);
CREATE TABLE "courses_levels" (
  "couse_id" int NOT NULL,
  "level_id" int NOT NULL
);
CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar NOT NULL,
  "course_id" int NOT NULL
);
ALTER TABLE "courses_levels" ADD FOREIGN KEY ("couse_id") REFERENCES "courses" ("id");
ALTER TABLE "courses_levels" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");
ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");
ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");
ALTER TABLE "students_courses" ADD FOREIGN KEY ("student") REFERENCES "users" ("id");
ALTER TABLE "students_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
INSERT INTO levels (type) VALUES ('beginner'), ('medium'), ('advanced'); 
INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin'); 
INSERT INTO categories (name) VALUES ('programming'), ('finance'); 
INSERT INTO users (name, email, password, age, role_id) VALUES ('Eliana', 'eliana-2233@gmail.com', 'root', 30, 1), ('Eva', 'evisgut-28@hotmail.com', 'root', 31, 1), ('Jose', 'jose_valderrama@gmail.com', 'root', 26, 2), ('Alejandro', 'alejandro@gmail.com', 'alejo', 30, 2), ('Benjamin', 'benjamin000@gmail.com', 'benja777', 29, 2), ('Juan', 'juan123@gmail.com', 'juancho', 22, 3); 
INSERT INTO courses (title, description, teacher, categorie_id) VALUES ('fundamentals', 'this course will cover the topics of HTML, CSS, JS', 4, 1), ('back end', 'the whole database issue will be seen', 3, 1), ('accounting', 'in this course you will see accounting tables', 5, 2); 
INSERT INTO courses_videos (title, url, course_id) VALUES ('html', 'https://www.youtube.com/watch?v=rbuYtrNUxg4', 1), ('node.js', 'https://www.youtube.com/watch?v=yB4n_K7dZV8', 2), ('tablas_contabilidad', 'https://www.youtube.com/watch?v=i2FPueaWc2M', 3); 
INSERT INTO students_courses VALUES (1 , 1), (2, 2), (1,2);